Add matched imputation
PSLmodels/synthimpute pull request #45
Opened 2021-07-18 11:51 UTC by nikhilwoodruff

This adds a bisection routine to the random forest imputation to match an aggregate.

Added support for MicroSeries and MicroDataFrame inputs, but without needing microdf as a dependency.

2021-07-19 05:00 UTC, MaxGhenis reviewed
Awesome, thanks @nikhilwoodruff. Though do you think we need a separate function from `rf_impute`? Might require a helper function or something, but it feels like we could just add `new_weight` and `target` args to to `rf_impute`.

Could you also add a test?

2021-07-26 12:23 UTC, nikhilwoodruff commented on synthimpute/rf_impute.py
> +    mean_quantile = bisect(aggregate_error, 0.01, 0.99, rtol=0.05)
Yep, done

2021-07-26 12:23 UTC, nikhilwoodruff commented on synthimpute/rf_impute.py
> +        quantiles = rng.beta(a, 1, x_new.shape[0])
Agreed, yep

2021-07-26 12:55 UTC, MaxGhenis requested changes
nice thx

2021-07-26 12:55 UTC, MaxGhenis commented on synthimpute/rf_impute.py
> +    if rf_model is None:
shouldn't the `.fit(...)` go in here too?

2021-07-26 12:55 UTC, MaxGhenis commented on synthimpute/rf_impute.py
> +        rf_model (ensemble.RandomForestRegressor): The pretrained model to use.
```suggestion
        rf_model (ensemble.RandomForestRegressor): The fitted model to use.
```

2021-07-26 12:55 UTC, MaxGhenis commented on synthimpute/rf_impute.py
> +        a = mean_quantile / (1 - mean_quantile)
these three lines could be their own function to reduce duplication with 128-130 and 137-141, e.g. 
```
def get_result(rf, x_new, mean_quantile):
    a = mean_quantile / (1 - mean_quantile)
    quantiles = rng.beta(a, 1, x_new.shape[0])
    return rf_quantile(rf, x_new, quantiles)
```

2021-07-26 12:55 UTC, MaxGhenis commented on synthimpute/rf_impute.py
> +        rng = np.random.default_rng(random_state)
can remove this

2021-07-26 13:02 UTC, nikhilwoodruff commented on synthimpute/rf_impute.py
> +        rng = np.random.default_rng(random_state)
Done

2021-07-26 13:10 UTC, nikhilwoodruff commented on synthimpute/rf_impute.py
> +        a = mean_quantile / (1 - mean_quantile)
Added

2021-07-26 13:10 UTC, nikhilwoodruff commented on synthimpute/rf_impute.py
> +    if rf_model is None:
Yep, changed

2021-07-26 13:20 UTC, MaxGhenis commented on synthimpute/rf_impute.py
> +    if rf_model is None:
should this all assign `rf_model` instead of `rf` so the `else:` piece can be deleted?

2021-07-26 13:20 UTC, MaxGhenis commented on synthimpute/rf_impute.py
> +            a = mean_quantile / (1 - mean_quantile)
use `get_result` here

2021-07-26 13:53 UTC, nikhilwoodruff commented on synthimpute/rf_impute.py
> +            a = mean_quantile / (1 - mean_quantile)
Done

2021-07-26 13:55 UTC, merged